divide code into components
XBOT-FTC/FTC-Scouting-App pull request #29
Opened 2024-10-17 00:10 UTC by NormalDuck

There are 3 new components:
`ScoringInput`: A wrapper around `NumberInput` but you can add text
`CheckboxText`: Checkbox but you can add text to describe what the checkbox does
`PhaseToggle`: A component that takes a array and builds a button group.

2024-10-17 00:17 UTC, Jxwoon requested changes

2024-10-17 00:17 UTC, Jxwoon commented on app/auto/page.tsx
> -                auto: { ...localDraft.auto, highSpecimen: val },
Missing the specimen logic

2024-10-17 00:31 UTC, NormalDuck commented on app/auto/page.tsx
> -                auto: { ...localDraft.auto, highSpecimen: val },
fixed it

2024-10-17 00:37 UTC, Jxwoon requested changes

2024-10-17 00:37 UTC, Jxwoon commented on app/end/page.tsx
> +            defaultValue={localDraft.end.net}
NIT: fix scheme

2024-10-17 04:56 UTC, NormalDuck commented
I have made changes to the most of the schema and added some new components. The visuals should match the actual matches. I didn't remove `final` page since I might need it later.

2024-10-17 05:48 UTC, johnylamw requested changes
AscentMap needs to modified to also include a "none" state. Right now, the options are either "Observation" or "Level x". There should be an option for when a robot does neither of these.

Additionally, refactor all instances of "Acent" to "Ascent" for proper spelling since it may confuse people working on the code. There might be a select all option in your code editor to refactor all instances of it rather than needing you to do it by hand.

2024-10-17 05:54 UTC, johnylamw commented
Also, a fun idea would be to create a VERTICAL slider for ascent states. Higher on the slider means the robot reached a higher climb. But that will require you to add labels to the axis. Maybe add some color coding to designate the level they're at. 

(just a fun idea if you're bored. I think the drop-downs that you have are more intuitive though and simpler to manage imo)

2024-10-17 21:21 UTC, NormalDuck commented
I have fixed **all** the typos with cspell. Added a new component in the newest commit and refactored the code to use the new component called `SelectInputText` Added none for ascent.

2024-10-17 23:25 UTC, johnylamw requested changes
"Observation" option missing for end-game and there is now 2 options for level 3. 
(small typos like these are natural - that's why pull requests exist)

There's also a "test" SelectInputText on the End pages. General practice would be to comment out or remove any sort of test interfaces considering that you're pushing into main which will be used in production. Personally I don't have any problems with that but just keep that in mind when you start working/interning in the industry. You can keep it there if you plan on further testing with it.

Overall, I like the new changes w/ the components and good job on fixing the spelling mistakes.

2024-10-18 00:26 UTC, NormalDuck commented
I didn't look carefully when I pushed the code😅

2024-10-18 01:29 UTC, johnylamw approved these changes
Good on my end. 
@Jxwoon thoughts?

2024-10-18 02:16 UTC, Jxwoon approved these changes
Don't want to hold up this PR. For the most part this looks good to go! Just left one nit comment that could be addressed in another PR or this one

2024-10-18 02:16 UTC, Jxwoon commented on app/end/page.tsx
> +          <option>Level3</option>
Nit: why is there two level3?

2024-10-18 02:18 UTC, NormalDuck commented on app/end/page.tsx
> +          <option>Level3</option>
I didn't look carefully my bad

2024-10-18 02:21 UTC, merged